### PR TITLE
bump 3.7.7

### PR DESCRIPTION
**Pull request by jafraustro**
comment two patches

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jafraustro** [comment]
@conda-forge-admin , please rerender

**Comment by jafraustro** [comment]
Hi @ocefpaf,
The build in #97 failed do to patches: 0003-VC9 and 0004-VC9

I'm not an expert—do you know if these patches are still necessary? Also, is there a reason why libarchive has not been updated? The build in #96 was successful.

**Comment by ocefpaf** [comment]
> I'm not an expert—do you know if these patches are still necessary?

We need to check if they were upstreamed or if they need to be refreshed due to code change.

> Also, is there a reason why libarchive has not been updated? The build in https://github.com/conda-forge/libarchive-feedstock/pull/96 was successful.

B/c no one had the time to do the above 😬

**Comment by AndresGuzman-Ballen** [comment]
Looks like the patches don't apply because the upstream code had made some minor modifications to some header files (like checking whether Windows version is XP or older): https://github.com/libarchive/libarchive/pull/2374/files. I don't know what the ramifications are for 0003 patch either (which needs to take into account new updates to CMakeLists.txt: https://github.com/libarchive/libarchive/compare/v3.7.4...v3.7.7#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)

**Comment by ocefpaf** [comment]
We probably need to refresh those patches then.

**Comment by AndresGuzman-Ballen** [comment]
@ocefpaf I refreshed them :) https://github.com/jafraustro/libarchive-feedstock/pull/1 I created the PR against jafraustro:3_7_7 so we didn't close this PR though

**Comment by jafraustro** [comment]
Hi, @ocefpaf 
can you give a look? please

**Pull request merged**
