### PR TITLE
Update to 3.3.2

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
cc @jakirkham

**Comment by stuarteberg** [comment]
Does anyone know why there is no linux build on anaconda.org for libarchive `3.3.2`?  Looks like only the Mac package is published.
https://anaconda.org/conda-forge/libarchive/files

**Comment by jakirkham** [comment]
Thanks @stuarteberg.

CircleCI has to use an SSH key to checkout the code (not sure why they do this, ask them). Unfortunately that expires periodically (around a year) and then we need a new one. Appeared that happened on the latest build so we didn't get a Linux package.

Just told the bot to generate a new SSH key for us in issue ( https://github.com/conda-forge/libarchive-feedstock/issues/15 ) and have triggered a [fresh CircleCI build]( https://circleci.com/gh/conda-forge/libarchive-feedstock/51 ), which should publish Linux packages shortly. Please let us know if that works or not.

**Comment by stuarteberg** [comment]
Thanks, @jakirkham!

**Pull request merged**
